language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5
env:
  global:
    - secure: "b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCkvaf+VA
wjo2ghS87u4NMVAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIBlZYw8YmtC6PecX
u5y3NXjProjkl+NvQqWYa8nOQy9iAAAAoFdCaEf/tujhiwzNBIjyUAcSLpAKFQGJJLlfx8
dT5L7XWSGAUVSpglE91FRb7oSch0yygAjn+yADAGeEX/Smd0yNXPnDrJTx4FRJ1t9YUxbY
ynd1MNXWECw3cDCLrJVHjzDsfLabP4Ikx5cVyuHQ8JdFSF/ZDHJ/NSyal4tH0fHBFpXbm4
VwyHNLfT2JK4wc4VJnerS+CU69wRF94q7WKK0="
before_install:
  - gem update --system
  - gem update --remote bundler
  - gem install bundler
  - gem install kramdown-math-katex
before_script:
  - git config --global user.name "$(git --no-pager show --no-patch --format='%an')"
  - git config --global user.email "$(git --no-pager show --no-patch --format='%ae')"
script:
  - git clone -b master --depth 1 "https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" _site >/dev/null 2>&1
  - rm -rf _site/*
  - bundle exec jekyll build
after_success:
  - cd _site
  - git add -A 
  - git commit -m "Updated to $(git rev-parse --short $TRAVIS_COMMIT) at $(date -u +'%Y-%m-%d %H:%M:%S %Z')"
  - git push "https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master >/dev/null 2>&1
branches:
  only:
  - source