language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5
env:
  global:
    - secure: "PcdYOwaOEgmJ2wAifRZGK8kH/nGgWU13vO6RBknfjHjvUjGDwXsw3z8oSjAS8Fmx+oMGjDnEnMncDcc4h2ztuRws5ODuQQLLKIJQ/9WSjTFwsody9xCrVWWKad8YRmTM1qKQYm11S+K8K2n0iR5XNJWOYK2iLJxviubhKNwkKgH0Tkak5I4mU79zWm6GQK+SyeihhoQy0EG7fPktK0+IkwKooSSbRXeJqlCRaV+Y1F55Gx7r5NI/xnGAlRUB/xAom8qaWnMXBJw+mYyHJ9RzA5pyPH7e5wxx9RgwUOuGCGxCYSrbx/Dua4Ce99gz/4hocQUX93PzCxpTINCafdA2cGlWDK6RSOTbMD6Ad/q0EAVWKPWIH5uJM2HPYWmBq1NkR0FVF/py20HoIxGdbzpq4vHZ63rYJ7msNCNb7/2KkJKGb5smk6lgngzZKr9CglhoJHvGH1pGwGitFgv12GS25+nWliQCPt1nj/Died13NwSE+Ujf0ozxPHJnQnYHHdKCSnVoyxskxr397yUkU6gJDvKxnDdrW8DS/cObPY2j0kZYRIEu/bThO0OnTsKorItwUeMot1FdNb7l4sBRpiZw/N0k7VTmwhWO5uI/C/79iFh28vBI3ep50ysxLd83Zaz5M+b3OzcnP1vogXJdhypo8+iYCyFV4nv/PCQFFxDDwVw="
before_install:
  - gem update --system
  - gem update --remote bundler
  - gem install bundler
  - gem install kramdown-math-katex
before_script:
  - git config --global user.name "$(git --no-pager show --no-patch --format='%an')"
  - git config --global user.email "$(git --no-pager show --no-patch --format='%ae')"
script:
  - git clone -b master --depth 1 "https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" _site >/dev/null 2>&1
  - rm -rf _site/*
  - bundle exec jekyll build
after_success:
  - cd _site
  - git add -A 
  - git commit -m "Updated to $(git rev-parse --short $TRAVIS_COMMIT) at $(date -u +'%Y-%m-%d %H:%M:%S %Z')"
  - git push "https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master >/dev/null 2>&1
branches:
  only:
  - source