theme: jekyll-whiteglass
# title: Quotidien
title-img: /assets/images/dotk_cpy.png
description: Learning by teaching
url: "https://dotkay.github.io"
timezone: PDT
lang: en
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-whiteglass.gemspec
  - screenshot.png
  - vendor

# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics: UA-105390377-1
comments: false

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Markdown settings
kramdown:
  syntax_highlighter: rouge
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  parse_block_html: true
  toc_levels: 1..6

jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/